### ISSUE TITLE
Clicking on image in profile open the image in fullscreen instead of opening a new tab of the tweet

### ISSUE THREAD

**Issue by seysn** [eramdam/BetterTweetDeck#156]
I never understood why Tweetdeck is acting like that, and I never found someone complaining about that or a plugin that correct that, but it annoys me so much.

When we're clicking on an image of a tweet, it open the image in fullscreen except on a profile, which is very annoying since it's pretty slow to load another page just to see an image, in addition of being in the Twitter interface, which makes no sense since I'm initially on Tweetdeck.

Maybe I'll make a pull request about that if I have the time but if someone wants to do it, do not hesitate !

**Comment by eramdam** [comment]
That's something annoying indeed, I wanted to find a way to fix it since day-one of Better TweetDeck.

The main issue is: How do you supposedly go back to the previous screen (here an user's profile)? You would have to somehow find a way to keep the old screen somewhere and show that you can go back to the said screen.

This could be as easy as simply hide visually one modal and show the fullscreen one instead.

Feel free to open a PR if you got time/want to though, I'm curious! 😄
