### ISSUE TITLE
When clicking on the play icon on a video it opens a google search of the image preview

### ISSUE THREAD

**Issue by PatrickClaybon** [eramdam/BetterTweetDeck#159]
Video of issue

https://youtu.be/mOnXA0bH_5g

**Comment by eramdam** [comment]
Already fixed in 3.3.5

**Comment by itemduper** [comment]
This issue seems to be back in 3.4.3

Here's an entire div block from a video, the element for the play button is highlighted in bold.

`<div class="js-media-preview-container media-preview-container position-rel width-p--100       is-video is-paused">     <div class="media-caret"></div>      <a class="js-media-image-link block med-link media-item media-size-large   is-zoomable" href="https://twitter.com/FutureFriendLP/status/901877891419529220/video/1" rel="mediaPreview" target="_blank" style="background-image:url(https://pbs.twimg.com/ext_tw_video_thumb/901877806300319744/pu/img/C-9qOKaFDqK87s7K.jpg)" data-media-entity-id="901877806300319744" data-external="true">  <div class="video-overlay icon-with-bg-round"> <i class="icon icon-bg-dot icon-twitter-blue-color"></i> <i class="icon icon-play-video"></i> </div>      </a>**<a href="https://images.google.com/searchbyimage?image_url=https://pbs.twimg.com/ext_tw_video_thumb/901877806300319744/pu/img/C-9qOKaFDqK87s7K.jpg" target="_blank" rel="url noopener noreferrer" class="js-show-tip reverse-image-search is-actionable " title="" data-external="true" data-original-title="Search image on Google">**</a>          </div>`

**Comment by eramdam** [comment]
@itemduper I went with a CSS solution to disable the pointer events on the link.

**Comment by itemduper** [comment]
@eramdam Cool!  I didn't even think about that because I don't touch CSS enough, but yeah [data-original-title*="Search image on Google"] { pointer-events: none; } also fixed it for me.

**Comment by eramdam** [comment]
@itemduper in that case I'm applying this on video thumbnails in columns only because I don't want to break the actual feature where it's supposed to work 🐱
