### ISSUE TITLE
AMO build outdated

### ISSUE THREAD

**Issue by Scrxtchy** [eramdam/BetterTweetDeck#193]
the build on addons.mozzila.org is dated to 22nd of June (3.3.10)
with 3.4.10 not anywhere to be seen with an official release, signed on unsigned.

Has the version been submitted and stuck in signing hell?
hard to report any issues if the version I am running does not reflect the latest release

**Comment by eramdam** [comment]
3.4.0 is stuck in the review hell it seems 😫  
![image](https://user-images.githubusercontent.com/1409924/28429899-4ef6f2fc-6d33-11e7-906e-589668531c41.png)

**Comment by Scrxtchy** [comment]
Been almost a month, I understand Mozilla asked to resubmit. Their practices feel pretty dated. But asking if it's been been resubmitted or are we waiting for a new major version?

**Comment by eramdam** [comment]
@Scrxtchy I actually got a reply from them and I have to change a bunch of things in the code and I'm not even sure it would still be okay after that. The add-on actually ended up in a weird state where they blindly approved a few builds but now I have to pass "admin review" (basically a full source code review) and I've been doing a lot of back and forths for the past few weeks 😞 

Hopefully this gets sorted out but it's taking a long time because every time I have to wait ~10days until they finally review.

**Comment by Scrxtchy** [comment]
Would it be worth just publishing presigned extensions to the github releases?
Some people use versions of firefox that allow running on unsigned content, from folders instead of zip(xpi)

Forever waiting

**Comment by eramdam** [comment]
@Scrxtchy Mozilla recently changed their review process so hopefully AMO build won't be stuck in review hell for weeks anymore 😄 https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/30839577-29322a60-a2b6-11e7-9d37-18f19380f0eb.png)
Feels good
