### ISSUE TITLE
More transparent "Edit" functionality

### ISSUE THREAD

**Issue by ViTheDeer** [eramdam/BetterTweetDeck#243]
The "Edit" functionality should be made more transparent and user-safe.
We should avoid users accidentally deleting tweets (and the likes/RTs/threads that come with it) without their knowledge
My suggestion: Don't delete the original tweet until you are finished composing the replacement tweet and hit "send".
Also, I would recommend putting hint text somewhere in the tweet composer column that explains the tweet will be deleted once they are finished editing it.

**Comment by pixeldesu** [comment]
Well, the user will see the tweet is deleted, and they have all text and media back at hand, so I don't see why it's not _user safe_.

Also, considering the Edit feature is inside a context menu, "accidentally" clicking it should be a relatively rare case.

The suggestion of deleting a tweet with the edited version being sent also does not work to be implemented as easily as the current way is done. We are implementing custom functionally accessing TweetDeck functions and filling data back in, a relatively _pain-free_ way to do stuff, also less prone to breaking with updates. 

Hooking in somewhere inbetween having a tweet sent and then deleting an older one is definitely more complex than the current solution.

**Comment by EntranceJew** [comment]
I can see rationale for adding a warning under the edit tweet option as a disclaimer. However, the edit button itself can't always keep track of the tweet being edited. 

The way the current code works is via getting as much context from the conversation/column as it can, and in some cases, the data is missing. It's entirely likely that an individual column or tweet could go missing before a tweet finishes posting which would complicate finding the tweet itself to delete.

It would be possible to attach to the edit button just once but since we don't have a way to keep track of the composer's state (very complex, internally -- not even sure when all or part of the code is used) -- the edit button as-is has to call it several times just to work because it was never even meant to allow attaching as much to the composer as it currently does.

This basically means that we can't fully understand the state of the composer and we try our best not to, we just bounce events at it and hope it doesn't go terribly wrong -- but to do anything further would require understanding the composer state better.

**Comment by eramdam** [comment]
I'll consider this fixed as https://github.com/eramdam/BetterTweetDeck/pull/246 is merged in master and will be in the next stable build
