### ISSUE TITLE
Accessibility Features

### ISSUE THREAD

**Issue by MBLAHO13** [eramdam/BetterTweetDeck#271]
Hi all,

Twitter allows you to compose image descriptions once you enable it in settings: https://support.twitter.com/articles/20174660 These image descriptions help people with vision issues enjoy images and visual content just like we can. Tweetdeck does not support image descriptions, unfortunately. I've sent Twitter feedback about this, but the chances of them actually implementing it is slim. 

Could you add an image description feature? Here's a quick use case OTOH:

- User wants to upload image via Tweetdeck.
- User enables Image Descriptions on Twitter.com settings.
- User drags image into BTD interface.
- A button appears with the label "description".
- The user clicks button, a text field with Twitter's description limit appears.
- The user types their description.
- The user clicks Tweet.
- The user's tweet appears with screenreadable alt-text, served by Twitter. 

I can't find anything in media upload API documentation, so I'm not sure what the parameters are for uploading with descriptions.

Here are pictures of the feature on Twitter.com: 

![image](https://user-images.githubusercontent.com/3543313/32692355-9b3a36b4-c6e4-11e7-8767-25bbe77c3e9b.png)
![image](https://user-images.githubusercontent.com/3543313/32692360-bc189880-c6e4-11e7-81aa-38c926ae737b.png)

**Comment by eramdam** [comment]
As much as I agree that TweetDeck should support that, I'm not sure I can do something on my end that would not require some changes on TweetDeck's API. I will investigate but I can't promise anything.

**Comment by eramdam** [comment]
Okay so here's what I found after investigating/thinking about how this feature _could_ be implemented:

We need to attach descriptions to images, which in reality means two things:

1. Build the UI to do so. While not hard would take quite some time, but I'm not worried about that specifically.
2. Find a way to send that information to Twitter's API. That's the biggest catch, to do so we need to mess with the way TweetDeck calls the Twitter API. That's something both very hard and very risky because we don't know the code that does this and it's very easy to break something if we're not careful enough.
And this is not even considering the fact that TweetDeck may have its own endpoint for media posting, meaning it may just not support whatever field is needed for the description altogether, making it simply impossible to add that feature.

**Comment by pixeldesu** [comment]
@eramdam seems to be `media/metadata/create`

https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-metadata-create

**Comment by eramdam** [comment]
I found a (possible) way to add the metadata to a given image, so there's hope!

**Comment by eramdam** [comment]
Turns out TweetDeck added this in today's update 🎉 https://twitter.com/BetterTDeck/status/1014187374501220352
