### ISSUE TITLE
Req: intercept/prevent tweet deletions, instead perhaps gray-out?

### ISSUE THREAD

**Issue by jxyzn** [eramdam/BetterTweetDeck#278]
Often, I'd like to finish reading a tweet that appeared at the top of my timeline, but is deleted seconds thereafter.

I was wondering if it might be possible to intercept that deletion and instead alter the display of that tweet (red striped background?) to make it clear that it's no longer "live" (probably removing or disabling the reply/fave/retweet buttons as well).

**Comment by eramdam** [comment]
As much as I see the use-case, I'm not confortable implementing something like this for multiple reasons:
1. If anyone deletes a tweet, it's not for it to stay displayed on a given client. That seems dangerous at best and abusive at worst.
2. It would take a lot of work to implement this without messing up with TweetDeck's internal logic because you'd have a tweet living inside TweetDeck's model that's actually not existing anymore, I assume this would break a lot of things for a very small gain.
