### ISSUE TITLE
Add an option to import and export the list of people you follow. (e.g. for transferring to another account)

### ISSUE THREAD

**Issue by Ailean** [eramdam/BetterTweetDeck#287]
Hi,

Is there a way BTD can add an option to export the list of people you follow and import it on e.g. a different account. This could be a way to change accounts without having to rebuild your following list if a name/handle change isn't suffice.

I think it is possible with some apps seeing as some accounts can mass follow whole lists. However I am not sure if it is allowed on all apps or that it is possible in BTD.

Thanks!

**Comment by pixeldesu** [comment]
This is technically speaking, possible.

We can grab a list of the people you follow, only based on their canonical IDs, not their names. So an export could work.

Now the problems start:
* The following-endpoints and TweetDeck functions want a username and not the user ID, so that would have to be _translated_ which takes up API actions
* Importing and re-following a huge list of followers takes up a lot of API requests. There are limits on the usage (15 requests per 15 minutes) and this action would most certainly oversaturate this by quite a bit, except we make it exceptionally slow.
* Twitter has safety measures (against spam) which basically lock new accounts that start following a lot of people after creation. So the behaviour you explain here is basically a ticket to getting suspended/locked quickly.

So, it's possible, but it needs a lot of consideration and a safe-to-use implementation that does not lock out users on usage. I'd deem this pretty low priority.

**Comment by Ailean** [comment]
It's good to hear it is possible and I agree with you that it is pretty low priority. Thanks for investigating though.

**Comment by eramdam** [comment]
I feel like the main obstacle of this is the time that it would take to import a following lists without hitting the rate-limit. That would mean having to keep TweetDeck opened to do it and that sounds....very unpractical 🤔

**Comment by EntranceJew** [comment]
We could import the data for the users and then gradually import then passively, slowly removing them from the queue in accordance with the rate limits and some sort of additional measure to minimize but not avoid new follow spam, mostly as an affordance for the user to follow people without the import burning all the available follows.

**Comment by ajcrwl** [comment]
Well, if simply following people one by one from your user/follows tab is not what you need, then I think there's a much easier way to do this without changing BTD. It will require a lot of copy-pasting and clicks to be done but in the end the goal will be achieved just fine. **This method relies on lists**:

1. Go to [twitlistmanager.com](twitlistmanager.com), sign in with the account from which you want to export usernames. It shows 100 users per page which is very convenient. Select and copy all text starting with the first user name and ending with the last. Don't worry about checkboxes.
2. Go to Tweet Deck with your second account and make a list. 
3. Click Edit list -> Add multiple users. Paste the text you copied and import. It allows only 100 names at a time, but you already have max 100 names from Twitlistmanager page.
4. Repeat steps 1-3 for each page on Twitlistmanager.
...
6. Manually follow everyone on the list.

There are a few things to keep in mind with this method:
- If you follow any people who have locked their accounts, then the list should be public, otherwise those users won't be added. If there are no private accounts, feel free to make a private list, no one will know >:-) Alternatively, manually refollow locked accounts without adding them to anywhere and keep your list private, TweetDeck will import only public accounts which you can follow later. _For this purpose public lists are inconvenient, because people can unsubscribe from them and you'll lose their names._
- Each list can hold only 5000 users, so keep an eye on numbers. Make multiple lists if necessary.
- Be careful when following people manually, twitter's anti-spam measures still apply.

Just my 2¢.

**Comment by eramdam** [comment]
I'm closing this as the feature itself would be inconvenient to be inside a browser extension and there are better alternatives listed in the thread.
