### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by ipugsiehd** [eramdam/BetterTweetDeck#290]
For me; (Windows & Google Chrome) - GIFs don't seem to work in Direct messages. The message sends but the GIF transfers over to a tweet. In addition, I believe a GIF icon to add them within replies and a dedicated button within messages would be sweet,

**Comment by ipugsiehd** [comment]
In addition, I noticed the GIF's get cached and uploaded - it may be a good idea to add the option for it to just paste a link (which also shows the GIF)

**Comment by eramdam** [comment]
1. GIFs don't work in DMs but there's nothing I can do because it's a bug on TweetDeck's API side
2. Adding a gif button in the inline reply would mean have another custom UI for that very specific case + you'd get popped out as soon as you add a file anyway so I really don't see the point in bothering
3. I could maybe do that but I don't really see the point, and keep in mind that non BTD users will just see a boring link.
