### ISSUE TITLE
A way to auto-mute people who has blocked you

### ISSUE THREAD

**Issue by JuanjoSalvador** [eramdam/BetterTweetDeck#323]
By default, Twitter don't allow you to view tweets from people who has blocked you. There is a little security issue with this, in vanilla twitter/tweetdeck: if anyone retweets any tweet from that people, you will be able to see it. And this sucks, to be honest.

Could be a way to mute automatically these people on Tweetdeck?

**Comment by pixeldesu** [comment]
That's not a security issue, that's behaviour from Twitter itself. You'll also see Retweets on any other client, if you have another user blocked.

There is no way to achieve this, since we have no way to check if a user has blocked us or not. TweetDeck not loading tweets from blocked users profiles simply is a negative effect of TweetDeck being unable to load them (via a "no permission" request).

The only thing you could do is muting the retweets of a blocking user using BetterTweetDeck, but of course manually.

**Comment by JuanjoSalvador** [comment]
It's something, I guess. Thanks @pixeldesu!
