### ISSUE TITLE
Mute tweets from a certain language?

### ISSUE THREAD

**Issue by Mohamed3on** [eramdam/BetterTweetDeck#327]
I'm wondering if we could have this feature where you could mute all tweets in Russian or any language?
Since we already could filter columns based on language which means there's a way to know a tweet's language?

**Comment by eramdam** [comment]
It'd be rather easy to do so since Twitter exposes a "language" field on every tweet (at least it did last time I checked). But language detection is never 100% accurate so I felt like you could easily run into false-positives. If it's something that people really want I might get around implementing it
