### ISSUE TITLE
Standalone BetterTweetDeck

### ISSUE THREAD

**Issue by GrantRVD** [eramdam/BetterTweetDeck#340]
Due to problems I had with TweetDeck automatically messing up some of Chrome's configurations (namely, overwriting Chrome's name in my `.local/shared/applications/` settings whenever I tried to create a shortcut on the launch bar), I use TweetDeck as a standalone application using a short [electron-based app](https://github.com/mikebell/tweetdeck-desktop) I found on github. The problem, of course, is that my BetterTweetDeck enhancements are gone, although I have the benefit of twitter not being handled through a browser anymore.

Since I built the app on my local machine, I was originally planning to just play around and see if I could get BetterTweetDeck's CSS and other scripts working with it, but since the scripts in the linked repository are actually pretty small, I took a look at the Contributing guidelines here and figured I'd ask if there's any interest in adding a standalone electron build to this repository itself. I'm a rookie when it comes to electron, but I can understand well-enough what the code in the other app is doing that I think it wouldn't take too much work. In fact, it looks like the only think really needed is an analog for `index.js`, besides adding electron as an optional dependency. I don't think the additions would interfere with the automated builds for the browser extensions.

If I managed to get something working on my own fork of this project, would there be any interest in me tidying up the code and documentation and submitting a pull request? Perhaps someone with more experience has already tried to do something like this and knows why it wouldn't work? Thanks for you time!

**Comment by eramdam** [comment]
It's not that easy. Given the way the extension is currently written, there's no easy way to make it work inside an Electron app because it's heavily dependent on the WebExtensions APIs for things like settings storage and communication between the content script/injected script. 

You'd need an abstraction layer to handle the messaging/storage on both Electron and WebExtensions platforms, it's not impossible but it would be a damn pain in the neck to do with the current codebase.

I'm working on a full rewrite in a specific branch, it's still at its early stages but hopefully it will make the abstraction of storage/communication a bit easier so down the line encapsulating the extension into an Electron app _would_ be a bit more easy than it is right now.

By all means if you feel like doing this on your own fork and suceed, go for it, maybe I'm missing an obvious solution 😛 But I'll still be working on my rewrite in parallel (I don't have any ETA for it just yet anyway...)
