### ISSUE TITLE
Group Conversation Lag

### ISSUE THREAD

**Issue by ipugsiehd** [eramdam/BetterTweetDeck#356]
While viewing (in addition to opening/closing) group chats using (even only) the BetterTDeck add-on, any group chat will lag and stutter, while it's had messages in the last few moments (and/or you've not opened the chat before) - I've noticed a black box appears in the top left of the text box for messages too.

Essentially, in a sum-up - BetterTDeck seems laggy in group chats (at least for me) and as rude as it may seem, but me not wanting it to come off that way - I'd like to see optimisation overall, as performance is the only thing that seems to hold me back from enjoying the add-on fully.

**Comment by pixeldesu** [comment]
Group chats and direct messages are broken by design, it's not BTDs fault they lag, and we already removed all features from the Messages column to ensure better performace

TweetDeck's way of loading tweets into group chats works at 100 at a time, so the first time it loads...10+ or so messages, then 100, then 200, increasing with each opening of the group chat. So, the more often you open a specific chat in the Messages column, the more the performance decreases.

You can try this out without BTD enabled, it will always get slower the more you open it.

This is confirmed by the TweetDeck team and...nobody knows, not even they, when they will refactor this.

There is no way to fix this other than refreshing if a chat becomes too slow.

**Comment by ipugsiehd** [comment]
Thank you.
It does, of course, happen still, without, which I failed to mention, however it seems to happen far more often with BTD than others, however, I didn't know what you said was actually a thing. Do you know if possibly the update supposed to release tomorrow, could help this?

**Comment by pixeldesu** [comment]
I could discuss with @eramdam if implementing a feature to limit loaded messages to something like "10 per load" would make sense, as I know how that works.

That's just a kinda "temporary" fix, as if you open it enough with that on it will also turn slower, it just delays the slowdown.

And I'd need to put it behind a feature switch as the behaviour might annoy people that are used to having 100 messages show up and don't mind or never noticed the slowdown.

**Comment by ipugsiehd** [comment]
That'd be appreciated - thank you for your help, however the outcome! <3
