### ISSUE TITLE
Instagram Missing from Firefox

### ISSUE THREAD

**Issue by TwisterMc** [eramdam/BetterTweetDeck#365]
The Firefox extension doesn't have Instagram image rendering.

I'm on Mac (latest version)
Firefox 61.0.1 
Better TweetDeck v3.7.8

**Firefox**
![firefox](https://user-images.githubusercontent.com/46997/42607709-ea8db834-8549-11e8-9811-e19e968f0df5.png)

**Chrome**
![chrome](https://user-images.githubusercontent.com/46997/42607708-ea7c7bc8-8549-11e8-9ea4-f9637abd5b71.png)

**Comment by eramdam** [comment]
This is unfortunately "by design".

Mozilla reviewers refuse extensions that embed code that they can't verify the source of. And the Instagram embed code is one of those, so to be able to pass Mozilla's validation I had to stip out Instagram entirely as it relies on Instagram's closed-source embed script 😞

**Comment by TwisterMc** [comment]
Aww sad. Maybe put in a note that says that so you don't get the same question over and over and over.
