### ISSUE TITLE
[Enhancement] - Ability to mark read below current tweet

### ISSUE THREAD

**Issue by Athanasius** [eramdam/BetterTweetDeck#384]
I love the 'mark all read' feature, but at times I both want to read all of a column and haven't yet done so.  If there was a "Mark tweets below this one as read" (label can have a shorter name, I'm being specific for the purpose of this request) option on the per-tweet menu it would help me then pick up again later.  This would be especially helpful as I use BTD both in Linux and Windows.

Having to scroll-scroll-scroll back down whilst looking out for tweets I recognise is a pain.  Being able to just do so to the current bottom knowing that's where to pick up from would be great.

Alternatively a key bind to mark the current highlighted tweet as read would also work, I could then start from the bottom and use this rather than scrolling.

**Comment by pixeldesu** [comment]
This won't work, as the way how tweets are loaded in TweetDeck is not sustained nor saved with a read-marker across sessions.

TweetDeck always just loads the 40 last tweets of a column (additional 40 the further you scroll down), but doesn't have any logic to jump to a certain tweet in the column view itself (even less if it never has been loaded by TD before).

We had the same suggestion on Twitter already, where someone asked us to implement TweetMarker, which is a popular solution to sync timeline reading progress across clients. Sadly, due to the aforementioned logic on how columns work in TweetDeck, it wouldn't work to add a feature like this, and it most certainly would break very easily too.

**Comment by eramdam** [comment]
Closing for the above reason.
