### ISSUE TITLE
Extremely bad performance when navigating DM's

### ISSUE THREAD

**Issue by Lucas7yoshi** [eramdam/BetterTweetDeck#396]
Navigating DM's or sometimes other menus with BTD enabled causes extremely bad and annoying freezes, also when you send a message or receive a message there a lag spike

I cannot get this to occur with BTD disabled at all

Issue: lag going back and forth in dms/sending/receiving (essentially any changes in the DMS tab)

Causes: 
Opening dm group chat
Sometimes individual group chats
Sometimes navigating other menus on tweet deck

This is an extremely annoying issue that is making me wonder if its even worth using BTD for image pasting/emojis over regular TD

**Comment by NuroDev** [comment]
This lag issue is actually an issue with stock TweetDeck and not BTD. It's been an issue for a very long time and BTD has tried to add features previously to help optimise TweetDeck DM's but not much has really worked sadly.
There is even a previous issue discussing the issues: #80 

Since TD is back in active development again they have been making a lot of changes recently, so hopefully they have plans to go back and rework their DMs system to be more optimised and run smoother 🤞

**Comment by eramdam** [comment]
As @NuroDev said, there's not much that can be done on BTD's side.
