### ISSUE TITLE
Add support for un-squashing media

### ISSUE THREAD

**Issue by HunterZ** [eramdam/BetterTweetDeck#429]
I run with column width set to 99%, and for some reason this causes images to get heavily cropped in the vertical dimension, regardless of media size preference:
![image](https://user-images.githubusercontent.com/108939/62010129-749a1880-b11b-11e9-890d-3b19b24abc24.png)

Would be nice if there was some option to make media show up at proper dimensions / uncropped when using custom column widths.

**Comment by pixeldesu** [comment]
As a quick fix, you can put the following CSS into the "Custom CSS" section in the BetterTweetDeck settings:

```
.media-preview {
    max-width: 300px;
}
```

That should solve your issues (and allow for own customization, as I set it to be roughly the size of the default column width here).

Not sure if we will go and implement this as an actual feature. Only with the storm of people coming from Web Twitter a lot of people have been requesting something along the lines of single-column modes and styling and it's a rather tough task to get that going easily, especially since any sort of CSS/layout change might get hit badly by TweetDeck, as they are actively developing and iterating on it as well.

**Comment by HunterZ** [comment]
Awesome, thanks. I also needed to set media preview size to medium for some reason.

Might be better if I could increase the height too, but at least it's not cropping badly anymore.

BTW, setting column width to 99% and using the sidebar to switch columns gets really close to a single-column experience.
