### ISSUE TITLE
Alternate webfonts?

### ISSUE THREAD

**Issue by ajkandy** [eramdam/BetterTweetDeck#457]
It'd be nice to have the option to use a selection of popular webfonts to customize the experience, loaded from Google Fonts, or specifying a locally installed / system font.

- Roboto
- Open Sans
- Public Sans
- IBM Plex
- Lato
- sans-serif 
- serif
- system (i.e. Segoe UI on Windows, San Francisco / Helvetica on OS X, etc)
- Local font (navigate to font file to get the path, or invoke system font palette if available?)

**Comment by eramdam** [comment]
Re: web fonts. Could you use the Custom CSS feature for that? I tend not to mess with fonts especially since TD now uses the system stack but I assume it would work?

I'd need to check the local font part because I doubt that browsers would let us do that, and even selecting the local file would be tricky because we'd need to essentially store the font _somewhere_ and I have no idea if browsers let extensions just store binary data like that 😅

**Comment by ajkandy** [comment]
I didn't know there was a Custom CSS feature! Is it documented on GitHub?
I'll go check it out. Thanks!

**Comment by eramdam** [comment]
Not really but it's as straightforward as it gets, write CSS and 💥 
![Screen Shot 2020-07-22 at 9 34 47 AM](https://user-images.githubusercontent.com/1409924/88203093-a181ee00-cbfe-11ea-9062-c26e7fdf6af6.png)

**Comment by ajkandy** [comment]
Cool. I guess it would help to know what classes they use (knowing them
it's some generated framework stuff...sigh) but I think it'd be easy to
just do a global font replacement. :) Thanks!
