### ISSUE TITLE
[Feature request] Rescheduling media tweets?

### ISSUE THREAD

**Issue by JomSpoons** [eramdam/BetterTweetDeck#468]
Hi there. I run an account that posts videos and such every six or so hours and I try to stick to this schedule as much as possible. Whenever I want to rearrange the order of the scheduled tweet lineup I have to delete them and create a new scheduled tweets altogether with new times set. This is a huge hassle and can take a ton of time, so would it be possible to add this as a feature.

I hear that Twitter Ads has something along these lines but I'd rather not make a business account just for that, and it'd be meticulous switching back and forth between that and TweetDeck. So would it be possible to implement this as feature for BetterTweetDeck? It'd be a huge help to me. Thank you for your consideration.

**Comment by eramdam** [comment]
Hum, I have no idea if TweetDeck's API would even allow to modify a scheduled tweet's due date without reposting it. I'd need to dig into it but I can't make any promises, especially since this is all in an API that Twitter (obviously) doesn't document so at best it's possible but could break overnight and at worst won't be possible at all.

**Comment by eramdam** [comment]
Given that this would depend on TweetDeck's own API (who is undocumented and which I'm not supposed to hit), I can't reliably do that, and there's no telling if the TD team will tell me to f*** off if something goes wrong because of some code of mine 😬
