### ISSUE TITLE
[Feature Request] "See X New Tweets"

### ISSUE THREAD

**Issue by salromano** [eramdam/BetterTweetDeck#473]
With legacy Twitter shutting down and the new Twitter.com being less than ideal, I'm looking for a replacement in TweetDeck.

TweetDeck is great, but it is missing two key features that I utilize:

1) I'd rather the "See X new tweets" button appear than tweets auto-loading, like so:

![Untitled-2](https://user-images.githubusercontent.com/6616923/81461768-12774500-917c-11ea-944d-83bd00c776b1.png)

2) Regarding the title, I'd like it to display said number of new tweets, so I can see how many new tweets have been made even if I'm on a different tab, like so:

![Untitled-25](https://user-images.githubusercontent.com/6616923/81461786-258a1500-917c-11ea-9825-e9dc943dc17c.png)

Ideally, I'd like to disable mentions, etc. from appearing as part of that number, and for it to only reflect new tweets in my lists.

Is that something that can be done?

Thanks for creating such a great extension! And for considering my request!

**Comment by eramdam** [comment]
Since TweetDeck silentely killed/broke the ability to _not_ have tweets be streamed into columns, I feel like re-instating it would be very tricky and potentially risky because we might break something in TweetDeck's internals.

I'll eventually dig into it and see what I find but I can't promise anything 🙇‍♂️
