### ISSUE TITLE
Schedule a retweet with a GIF

### ISSUE THREAD

**Issue by llrs** [eramdam/BetterTweetDeck#508]
Many thanks for providing this tool it makes easier to manage multiple accounts.

I've been trying to retweet with a gif and it doesn't seem possible. Is this a twitter limitation or TweetDeck or something on BTD? If is on BTD could be included or planed? 

I have found any explanation on this on twitter side or here on any issues, but apologies if I missed them.

**Comment by eramdam** [comment]
There's a couple of things here:
1. TweetDeck doesn't support adding any kind of media to a retweet, despite all other official Twitter apps doing so. Adding that support would be tricky
2. The schedule part might have a server-side limitation that would be tricky to work around.

I had a random proof of concept for the first point, but it would require more polish and I expected the TD team to do it themselves at some point... 😬 

I'm going to close this as `wontfix` since this is something TweetDeck really should fix themselves, doing so at the BTD level would be wonky at best and brittle at worst.

**Comment by llrs** [comment]
Many thanks, I understand why it won't be possible.

Is TD actively maintained? I thought it wasn't any more, because at some point I found a page with updates done which last entry was on 2016 or something alike.
