### ISSUE TITLE
Add a link to favstar.fm

### ISSUE THREAD

**Issue by cmdrfletcher** [eramdam/BetterTweetDeck#58]
Add a link to the profile of a user on "favstar.fm" to the "..." context menu.

**"Show user on favstar"**

http://favstar.fm/users/twittername

![image](https://cloud.githubusercontent.com/assets/6803995/15121768/5a6b96de-161c-11e6-8be4-36a5a1ebb433.png)

**Comment by eramdam** [comment]
Great idea. Will see how doable it is.

**Comment by pixeldesu** [comment]
@eramdam @cmdrfletcher it is possible!

I just did some proof of concept, just copy that one (really long) line of JS into the JS console of your TweetDeck tab and see the magic happen:

https://gist.github.com/pixeldesu/24980c009114f0ee5d6b45892e355745

**Note:** Due to having no idea of the specific template conditions, this sometimes works and sometimes does not, but if it does, it opens a new tab with the tweet open on Favstar.

**Comment by eramdam** [comment]
@pixeldesu Nice! Is it me or your Gist is just doing a `.replace()` without actually replacing anything since the function is missing an argument? 😅

**Comment by pixeldesu** [comment]
@eramdam it does replace something, but you probably won't see because I replace the full context (I was too lazy to just search for an exact entrypoint and basically copied the entire template in)

**Comment by eramdam** [comment]
Oh okay. Well yeah, the only way to inject things inside the templates is to replace their content (I do that to keep the RT/Like indicator).

**Comment by eramdam** [comment]
@cmdrfletcher This has been added by https://github.com/eramdam/BetterTweetDeck/commit/e48e8054c1d4d1f55cf2ea18b62600bf136d70b7 and should be available in Better TweetDeck 3.3.10. Sorry for the long wait on this one 😛
