### ISSUE TITLE
Waterfox classic and 4.0.2 - no settings

### ISSUE THREAD

**Issue by Cnuut** [eramdam/BetterTweetDeck#583]
Hi I´m on **windows10** with **Waterfox classic**(2021.02 (64-bit)) and just updated to **BTD 4.0.2** and settings only show a blank page.
is it only me or is it incompatible?
:)

**Comment by eramdam** [comment]
Most likely. Waterfox Classic runs an older version of Gecko so I can’t guarantee support for it. I already don’t officially support waterfox in the first place.

**Comment by Scrxtchy** [comment]
Also having this issue on Firefox 76. It appears that this actually is an issue and causes the existing settings to not load at all, therefore the extension is no longer compatible at all on this version. It's `strict_min_version` should be updated

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/118988376-7ace4880-b9c4-11eb-947d-6bb4b43b34a8.png)
it appears that this was done only once for the 4.0.0 version, it's not something that seem to be been maintained, so unsupported browsers are indeed updating to unsupported versions, manually or otherwise
