### ISSUE TITLE
Tweetdeck Preview

### ISSUE THREAD

**Issue by garpu** [eramdam/BetterTweetDeck#653]
Granted, it's an unknown and looks like it just rolled out today, but what's going to happen with BetterTweetDeck and the new TweetDeck?  Will it be possible to use it to tweak the new TweetDeck layout? (Because narrow was too narrow, and medium was too wide.)

**Comment by eramdam** [comment]
Note: I'm pinning this issue, so future discussion about TweetDeck Preview stays here. Also, for simplicity's sake, I'll refer to current TweetDeck as "TweetDeck" and TweetDeck Preview as "**Gryphon**" (that's how it's called in the code)

Like I said in a [personal thread](https://twitter.com/Eramdam/status/1417505836662853633) I was given access to TweetDeck Preview yesterday morning, so I had time to play around with it. And while it is still pretty early and missing some key features (notable Teams/multi-account), I have some thoughts, and I think it's promising from a user perspective.

Gryphon uses the same tech stack as Web Twitter (the new, mobile-looking one), which means that it will get new Twitter features much, MUCH quicker. This means I (hopefully) won't need to play catchup with BTD and will be able to focus on "niche" and "fun" features that Twitter will never implement.

The downside of this is that most of BTD's code is now moot. It's a bummer, but it's not surprising. We knew this was coming. At least we now have something to poke out so we can start having fun with it 🙂

I can't make any promises because we have no timeline regarding the general availability of Gryphon, and there's still a lot of things to figure out. But I will be looking into supporting it when it is widely available.
The feature set will probably be much smaller because some features have been [sherlocked](<https://en.wikipedia.org/wiki/Sherlock_(software)#Sherlocked_as_a_term>) and some wouldn't make sense.

In any case, there's not much to worry about in the near future and I'm hopeful that BTD will be able to do _something_, even if it starts with the basics at first once TweetDeck Preview is live for all 😁

**Comment by clairernovotny** [comment]
Looks like you can set/clear a cookie to opt-in/out of the preview. Might be a good option for BTD to offer?

https://twitter.com/wongmjane/status/1417520652634836992?s=21

**Comment by eramdam** [comment]
> Looks like you can set/clear a cookie to opt-in/out of the preview. Might be a good option for BTD to offer?
> 
> https://twitter.com/wongmjane/status/1417520652634836992?s=21

Hum, yeah but I'm not a big fan of that because:
- There's no telling that Twitter will leave it like this. It's unlikely but they absolutely could add backend checks to make sure that only people enrolled in the preview are allowed to access it
- This option will become obsolete once Preview hits general availability, but maybe they'll keep the old version around after the fact? 🤷 😅 

If that becomes useful and stays relevant, I might look into something like that, but even then I feel like having a setting for that might be misleading because BTD won't be able to do anything there for a while 😁

**Comment by garpu** [comment]
I guess the two things I really missed were the gif button and some ability to fine-tune the size of the columns.  Small was too narrow, and medium was still too wide.

**Comment by eramdam** [comment]
> I guess the two things I really missed were the gif button and some ability to fine-tune the size of the columns. Small was too narrow, and medium was still too wide.

But preview does have a gif button? 😅 
![image](https://user-images.githubusercontent.com/1409924/126664868-d64c9f12-cd3a-40b2-bb3e-930338b31741.png)

**Comment by garpu** [comment]
Totally missed it! :)

**Comment by garpu** [comment]
ONe thing that seems to be missing in the preview that wasn't was to turn off retweets on a column. I really miss that, because my home gets really cluttered quickly.

**Comment by dixonge** [comment]
Got a popup to try out preview yesterday. Did not like the column width options, and no way to 'clear' content. Is there a way to use BTD in the preview yet?

**Comment by eramdam** [comment]
Closing this in favor of https://github.com/eramdam/BetterTweetDeck/issues/848
