### ISSUE TITLE
YouTube embeds from Twitter for Advertisers don't embed

### ISSUE THREAD

**Issue by SuperSajuuk** [eramdam/BetterTweetDeck#714]
**Describe the bug**
If someone posts a tweet from Twitter for Advertisers, and the embed card is a YouTube video, the video card does not appear on TweetDeck.

**To Reproduce**
1. Follow someone who uses Twitter for Advertisers [or go to the site if you use it yourself]
2. Post or receive a tweet from the user that has the source set to Twitter for Advertisers, where the embed contains a youtube video
3. Observe the lack of embed for the post.

**Expected behavior**
The YouTube video should correctly embed onto the bottom of the tweet, as it does with other tweets outside of TfA.

**Screenshots**
Not really a screenshot, but I observed this with the following tweet from McLarenF1: https://twitter.com/McLarenF1/status/1459159409398067207

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 64-bit, v2004 Build 19041.1237
- Browser: Google Chrome v95.0.4638.69 [64-bit]
- Version: BTD 4.5.2

**Comment by eramdam** [comment]
Unfortunately, this card is under the same name as the carousel ones that are causing issues, so they got axed when I disabled those as well in order to fix https://github.com/eramdam/BetterTweetDeck/issues/702

And since I don't control the code that renders the card, I can't do much because all I do is tell it it can render cards with a given set of names
