### ISSUE TITLE
Publish betterTW to the iOS safari extension store

### ISSUE THREAD

**Issue by ShadowJonathan** [eramdam/BetterTweetDeck#748]
Currently, betterTW is published to the macOS safari extension store, but with iOS 15, safari on iOS and iPadOS have the ability to run extensions as well.

I’d like to use tweetdeck on my iPad, as it’s wide touch screen could be ideal for quickly scrolling through feeds of tweets, and the interactions that BTW gives (single clear buttons, etc.) could drastically enhance that experience.

This isn’t a request to make BTW (make TW) touch-optimised, just to submit the extension for mobile safari as well.

**Comment by eramdam** [comment]
So I considered it when Apple announced that, and I had a build working fine-ish in the iPadOS simulator.

However, it's not as easy of an equation because:
- The "threat" of TweetDeck Preview rolling out generally at some point next year is going to get real soon and that'll be quite an ordeal to deal with.
- iOS/iPadOS Safari extensions are required to use non persistent background pages. This means I'd need to do the same for desktop, I attempted that [earlier this year](https://github.com/eramdam/BetterTweetDeck/pull/633) and it broke a bunch of random things 😅 I might look into it again because the benefits for desktop OSes are nice as well (battery life)
- While I think _most_ things should work just fine with a touch-based input, I might have to spend some time investigating/using the extension for myself to see if there are refinements to do. 
- I use `click`-based events in a bunch of places and I have no idea if those will work as-is or if I need to switch them to pointer-based events instead.
- Building/maintaining an iOS app (albeit minimal because it'd only include an extension) is also something I never did and have no idea of how much time it'd take. The App Store review process was already cumbersome to deal with on the Mac so I don't want to imagine how much more annoying it'll get with an iOS app thrown into the mix 😬 

This isn't a strict "I won't do it" but more a "maybe" but I wanted to lay out my reasoning 😅

**Comment by ShadowJonathan** [comment]
It's already quite enough to see a comprehensive response like this, thanks a lot!

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
