### ISSUE TITLE
Content warning detection is hiding notification content

### ISSUE THREAD

**Issue by ashridah** [eramdam/BetterTweetDeck#751]
**Describe the bug**
I have a twitter follower who has square brackets in their name, who occasionally likes posts I make. The Content Warning feature in Better Tweetdeck is causing the notification to show up weird and not display the notification correctly, resulting in it missing most of the context of the liked tweet. See the screenshot below for example.

**To Reproduce**

1. tweet something.
2. Have follower with name "[~name in square brackets and possibly tildes~]" like said tweet.
3. Examine the "notifications feed" and notice that the content warning detection has kicked in unexpectedly, and that even when expanded, the tweet is not displayed correctly.

**Expected behavior**
Even if the content warning behavior is going to kick in for a notification because the name of the person has square brackets around it, it should still display the entire tweet when expanded

**Screenshots**
As seen in the screenshot, the expanded notification doesn't show the actual tweet liked.

<img width="288" alt="Screen Shot 2022-01-04 at 9 23 32 AM" src="https://user-images.githubusercontent.com/3069777/148099638-faa2841c-2f35-4e3e-bd8b-106c0adbb020.png">

**Desktop (please complete the following information):**

- OS: MacOSX Catalina
- Browser: Firefox
- Version 95.0.2

**Comment by eramdam** [comment]
Good catch! I hadn't seen that... Their username must be "old" because Twitter doesn't let me add square brackets inside a display name 😅
![CleanShot 2022-01-04 at 17 05 58](https://user-images.githubusercontent.com/1409924/148144619-97be715d-447c-477f-bae1-4606077faaca.png)
 
In any case, the next release will have a stricter matching logic for "keyword less" content warnings, so this specific instance wouldn't happen anymore (because of the spaces), but I threw an additional check to _not_ apply the detection on notifications at all.

**Comment by ashridah** [comment]
Hm, interesting observation I want to say they only changed it to that in the past few years or so, it's not super old. It's possible that the client they're using allows for non-standard names, and it's just the normal twitter client that's forcing strict checking or something. Thanks for the response though!

**Comment by eramdam** [comment]
Actually, I ended up tweaking the logic to apply the detection on the real "content" of notifications, which seems more correct IMO 
![image](https://user-images.githubusercontent.com/1409924/148145306-aab4f62c-e754-4c9d-8991-05f29ff7e1b1.png)

**Comment by eramdam** [comment]
Fixed in 4.7.0!
