### ISSUE TITLE
Custom column width breaks fullsize media preview

### ISSUE THREAD

**Issue by contextnerror** [eramdam/BetterTweetDeck#813]
When using "Display fullscreen images à la Twitter Web" and "Display single images with their original aspect ratio (only for Medium and Large sizes)", the thumbnails become cropped when using a custom column width.

**Screenshots**
Native tweetdeck settings wide columns, large media, BTD fullscreen images and original aspect ratio enabled
![nocustom](https://user-images.githubusercontent.com/54487525/160370479-7382bd4b-4dac-4a7d-870b-4ae52e972ccd.png)

Same as above but with custom column width setting at 600px
![custom](https://user-images.githubusercontent.com/54487525/160370682-7fca2d83-a48a-4d1f-a937-b359232588c5.png)

Mac running Chrome and BTD version 4.8.5

**Comment by kuroshibolt** [comment]
Is there a way to force it to show the image full height? Because it seems ok in terms of width, but you can only see its true height (on portrait-oriented images) when the column width is below 200px.

![portrait-oriented-455px](https://user-images.githubusercontent.com/66945856/161384542-5e2d9817-aac6-40b8-97d5-e09818baf3c3.png)

![portrait-oriented-200px](https://user-images.githubusercontent.com/66945856/161384672-a72181ac-e8a4-4d09-a5ca-e4e4ebe6d75d.png)

On landscape-oriented images, it is working without any issues.

![landscape-oriented-455px](https://user-images.githubusercontent.com/66945856/161384553-c8798be9-40e2-4653-a6e9-60a4ee1cb87a.png)

![landscape-oriented-full-size](https://user-images.githubusercontent.com/66945856/161384556-9a710b3d-620e-42e2-87ab-bfd1dc4c86f0.jpg)


Keep up the good work!

**Comment by Wrizz** [comment]
Any solutions/fixes for this? I have tried custom CSS, but it doesn't work well (images get enlarged either too much and get blurry/pixelated or too little and appear cropped). I have also tried setting width and/or height to "100%" with custom CSS, but that just makes images not appear at all.
The "Image" settings in the "Tweet content" BTD settings don't make much (if any) difference. This is a bit weird, since it seems like a simple fix with CSS, but idk.
