### ISSUE TITLE
Lists are not loading anymore

### ISSUE THREAD

**Issue by Invicta76** [eramdam/BetterTweetDeck#873]
Hello,

It appears that ever since the new limited rates that everyone is complaining about, BetterTweetDeck is not displaying tweets from Lists anymore, all I get is a "Loading" animation https://gyazo.com/b1ab0cdfc4c48d40d3c11ecdcbe19862. Tweets do display if no Lists are being used as my first column includes all tweets and the rest of columns only contain tweets from lists. Been trying a different browser/reinstall but no prevail unfortunately. Tried in both Mozilla, Chrome and Brave browsers so far. The lists are loading just fine with TweetDeck, just not with BetterTweetDeck extension. I am aware you are not planning to work anymore on the extension but maybe this is something that wouldn't take long to address? BTD remains by far my favorite extension when it comes to social media, it would suck to switch back to the lame default tweetdeck.

**Comment by eramdam** [comment]
I just tried with vanilla TweetDeck and neither lists nor mentions/notifications load. I don't know how or why lists loaded for you but it must have been pure luck.

Either way, the endpoints return a 404 error or just don't respond so as far as I'm concerned, shit is just broken on Twitter's side because of Elon's bullshit so there's not much I can do.

**Comment by Invicta76** [comment]
Thanks for looking into it @eramdam, I appreciate. Hopefully they'll fix their shit, as I really don't want to drop BTD but Twitter been taking really stupid decisions one after another.
