### ISSUE TITLE
Handling of GIF profile pictures

### ISSUE THREAD

**Issue by babolivier** [eramdam/BetterTweetDeck#98]
Back in the days, it was possible to upload an animated gif as your profile picture. Users who didn't change their profile picture since then still have it animated.

Displaying those seems to be perfectly handled by TweetDeck (not animated here, but trust me, the PP is)

![td-gif-pp](https://cloud.githubusercontent.com/assets/5547783/18503695/bf70535c-7a5e-11e6-914a-639d29c18462.PNG)

However, the PP fails to display in BTD

![btd-gif-avatar](https://cloud.githubusercontent.com/assets/5547783/18503720/d43c4b74-7a5e-11e6-8594-d925c188356c.PNG)

Using the latest version, and minimalist mode enabled, if this can help.

**Comment by babolivier** [comment]
Update, this happens to all accouts which PP is in the GIF format, even if there's no animation. For example, this behavior has also been observed with [this account](https://twitter.com/DPRK_News).

**Comment by eramdam** [comment]
You have the option to disable GIF profile pictures I guess ? Also can you link me a tweet so I can easily display it in TweetDeck on my side?

**Comment by eramdam** [comment]
Hum I managed to find the tweet back and it works correctly here, is there any errors in the console? (most likely a network issue)

**Comment by babolivier** [comment]
Well, now that you mention it, it seems that my company's crappy proxy prevents my browser from opening a correct HTTPS connection between the image server (seems like there's a special one for GIFs pictures). I'll try again at home (haven't got much time on my personal computer for a few days) and close the issue if that's the case.

**Comment by eramdam** [comment]
Because if you have this option enabled
![screen shot 2016-09-15 at 8 58 31 am](https://cloud.githubusercontent.com/assets/1409924/18557145/98e44bb6-7b22-11e6-86c4-3dac44699b27.png)

Then I use an URL like this `https://images4-focus-opensocial.googleusercontent.com/gadgets/proxy?url=<original-gif>&container=focus&resize_w=720&refresh=86400` to have a static version of the gif.

You can simply disable this option if you don't care about GIF profile pictures being animated though (I'll make it disabled by default on the next release I think)

**Comment by eramdam** [comment]
I'll be closing that. Feel free to ping me if needed.
